name: jazzy

on:
  pull_request:
    branches:
      - jazzy
  push:
    branches:
      - jazzy

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    container:
      image: osrf/ros:jazzy-desktop
    strategy:
      matrix:
        os: [ubuntu-24.04]
      fail-fast: false
    steps:
      - name: Install deps
        run: sudo apt-get update && sudo apt-get install -y wget python3-vcstool python3-colcon-coveragepy-result
      - name: build and test
        uses: ros-tooling/action-ros-ci@0.2.6
        with:
          package-name: computer_vision
          target-ros2-distro: jazzy
          vcs-repo-file-url: ""
          colcon-defaults: |
            {
              "test": {
                "parallel-workers" : 1
              }
            }
